import json

import streamlit as st
from groq import Groq

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Innovation Process Navigator",
    page_icon="🧭",
    layout="centered",
)

MODEL = "llama-3.3-70b-versatile"  # free tier on Groq, strong instruction-following

# Ordered list of modules in scope for this refactor. Each entry is
# (key, display label). The key maps to prompts/module_<key>.txt.
MODULES = [
    ("0b", "0b — Problem Framing"),
    ("3", "3 — Idea Generation"),
    ("4", "4 — Concept Development"),
    ("5", "5 — Value Proposition Canvas"),
    ("6", "6 — QFD & Prototype Roadmap"),
]
MODULE_KEYS = [k for k, _ in MODULES]
MODULE_LABELS = dict(MODULES)

VPC_URL = "https://claude.ai/public/artifacts/eccc7f0a-e1e0-4e54-83d4-b6dfd12fb053"
QFD_URL = "https://claude.ai/public/artifacts/f1d67075-84a6-46dc-920d-ef66531cf5fe"

GREETING = """👋 **Welcome to the Innovation Process Navigator**

I'm an AI innovation coach designed to guide you from wherever you are today to a validated innovation value proposition you can present to any stakeholder.

This tool is part of the Certified Innovation Manager (CIM) program, based on the innovation management framework developed at the SEPT Competence Center, Universität Leipzig.

**How the process works**

The SEPT Innovation Process moves through three phases. In the **Fuzzy Front End** we frame the problem, explore the opportunity, and generate and select an idea. In **New Product Development** we turn that idea into a concrete concept, understand your customer, and plan a testable prototype. In **Commercialization** we build the go to market logic and articulate everything in business language.

Between these phases sit three **decision gates**: Idea Evaluation, Feasibility Evaluation, and Market Validation. At each gate I give you an honest verdict of Go, Conditional Go, or Stop. I will not simply wave you through.

Along the way I connect with two companion tools, the **Value Proposition Canvas** and **Quality Function Deployment (QFD)**, which you will find linked in the sidebar. I also give you a short **progress summary after every step**, so you can stop anytime and resume later without losing your work.

---

**▶️ Continuing a previous session?**
If you saved a **SESSION STATE** block last time, just paste it here and I'll pick up exactly where you left off.

**🆕 Starting fresh? Which describes you best?**

**A)** I have a digital solution or technical concept already built.
**B)** I see a problem or opportunity, but I don't know the solution yet.
**C)** I have several ideas and I need to decide which one to pursue.
"""


# ---------------------------------------------------------------------------
# PROMPT LOADING (cached)
# ---------------------------------------------------------------------------
@st.cache_data
def load_base_prompt() -> str:
    with open("prompts/base.txt", "r", encoding="utf-8") as f:
        return f.read()


@st.cache_data
def load_module_prompt(module_key: str) -> str:
    with open(f"prompts/module_{module_key}.txt", "r", encoding="utf-8") as f:
        return f.read()


def build_system_prompt(module_key: str) -> str:
    """Base rules + only the current module's instructions."""
    return load_base_prompt() + "\n\n" + load_module_prompt(module_key)


# ---------------------------------------------------------------------------
# GROQ CLIENT
# ---------------------------------------------------------------------------
def get_client() -> Groq:
    # Prefer a key the user entered in the sidebar; otherwise fall back to the
    # shared default key from Streamlit Secrets.
    user_key = st.session_state.get("user_api_key", "").strip()
    api_key = user_key or st.secrets.get("GROQ_API_KEY")
    if not api_key:
        st.error(
            "GROQ_API_KEY was not found in the Streamlit Secrets. "
            "Go to Settings → Secrets in Streamlit Cloud and add it."
        )
        st.stop()
    return Groq(api_key=api_key)


# ---------------------------------------------------------------------------
# SESSION STATE BLOCK (generated by CODE, not the model)
# ---------------------------------------------------------------------------
def render_session_state_block() -> str:
    """Format st.session_state.captured into the canonical SESSION STATE block."""
    cap = st.session_state.captured
    label = MODULE_LABELS[st.session_state.current_module]

    lines = [
        "=== SESSION STATE — Innovation Process Navigator ===",
        f"Entry route: {cap.get('entry_route') or '—'}",
        f"Innovation type: {cap.get('innovation_type') or '—'}",
        f"Classification: {cap.get('classification') or '—'}",
        f"Selected idea: {cap.get('selected_idea') or '—'}",
        f"Current module: {label}",
        "Deliverables captured:",
    ]

    deliverables = cap.get("deliverables") or {}
    if deliverables:
        for module_name, summary in deliverables.items():
            lines.append(f"- {module_name}: {summary}")
    else:
        lines.append("- (none yet)")

    lines.append(f"Open conditions / risks: {cap.get('open_risks') or '—'}")
    lines.append("=== END SESSION STATE ===")
    return "\n".join(lines)


def merge_captured(new: dict) -> None:
    """Merge extracted values into captured. New non-empty values overwrite old;
    empty values never wipe existing keys."""
    cap = st.session_state.captured
    for key, value in new.items():
        if key == "deliverables" and isinstance(value, dict):
            existing = cap.get("deliverables") or {}
            for module_name, summary in value.items():
                if summary:  # never overwrite with empty
                    existing[module_name] = summary
            if existing:
                cap["deliverables"] = existing
        elif value not in (None, "", [], {}):
            cap[key] = value


def _extract_json(text: str) -> dict:
    """Pull the first JSON object out of a model reply, tolerating code fences."""
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return {}
    return json.loads(text[start : end + 1])


def update_captured() -> None:
    """Separate lightweight API call: ask the model for a compact JSON summary of
    everything decided so far, then merge it into captured. Silent on failure."""
    try:
        client = get_client()
        convo = "\n\n".join(
            f"{m['role'].upper()}: {m['content']}"
            for m in st.session_state.messages[-8:]
        )
        instruction = (
            "You extract structured state from an innovation-coaching conversation. "
            "Return ONLY a compact JSON object, no prose and no code fences, with "
            "exactly these keys: entry_route, innovation_type, classification, "
            "selected_idea, deliverables (an object mapping module name -> one-line "
            "summary), open_risks. Use an empty string for anything not yet decided, "
            "and {} for deliverables if none. Do not invent information."
        )
        resp = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": instruction},
                {"role": "user", "content": convo},
            ],
            temperature=0,
            max_tokens=500,
        )
        data = _extract_json(resp.choices[0].message.content or "")
        if isinstance(data, dict):
            merge_captured(data)
    except Exception:
        # Keep the previous captured state and continue silently.
        pass


def parse_pasted_session_state(text: str) -> dict:
    """Parse a pasted SESSION STATE block into captured-shaped data.
    Returns a dict that may also contain a special 'current_module' key."""
    result: dict = {}
    deliverables: dict = {}
    in_deliverables = False

    label_map = {
        "entry route": "entry_route",
        "innovation type": "innovation_type",
        "classification": "classification",
        "selected idea": "selected_idea",
        "open conditions / risks": "open_risks",
    }

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("==="):
            continue

        if line.lower().startswith("deliverables captured"):
            in_deliverables = True
            continue

        if in_deliverables and line.startswith("-"):
            item = line[1:].strip()
            if item and item.lower() != "(none yet)" and ":" in item:
                module_name, summary = item.split(":", 1)
                deliverables[module_name.strip()] = summary.strip()
            continue

        if ":" in line:
            in_deliverables = False
            key, value = line.split(":", 1)
            key_norm = key.strip().lower()
            value = value.strip()
            if value in ("", "—"):
                continue
            if key_norm == "current module":
                # Match against a known module by its key prefix.
                for mkey in MODULE_KEYS:
                    if value.lower().startswith(mkey.lower()):
                        result["current_module"] = mkey
                        break
            elif key_norm in label_map:
                result[label_map[key_norm]] = value

    if deliverables:
        result["deliverables"] = deliverables
    return result


# ---------------------------------------------------------------------------
# API PAYLOAD
# ---------------------------------------------------------------------------
def build_api_messages(system_prompt: str) -> list:
    """Each call sends: base + current module prompt; the current SESSION STATE
    block as authoritative memory; and only the LAST 8 conversation messages.
    Full history stays in session_state and rendered in the UI."""
    api_messages = [{"role": "system", "content": system_prompt}]
    api_messages.append(
        {
            "role": "system",
            "content": (
                "CURRENT SESSION STATE (memory of everything decided so far):\n"
                + render_session_state_block()
            ),
        }
    )
    api_messages += [
        {"role": m["role"], "content": m["content"]}
        for m in st.session_state.messages[-8:]
    ]
    return api_messages


def run_assistant_turn() -> None:
    """Make one API call for the current module, stream it, store the reply, then
    refresh the code-generated session state. Assumes any new user message has
    already been appended and rendered."""
    client = get_client()
    system_prompt = build_system_prompt(st.session_state.current_module)
    api_messages = build_api_messages(system_prompt)

    with st.chat_message("assistant"):
        placeholder = st.empty()
        full_response = ""
        try:
            stream = client.chat.completions.create(
                model=MODEL,
                messages=api_messages,
                temperature=0.6,
                max_tokens=1500,
                stream=True,
            )
            for chunk in stream:
                delta = chunk.choices[0].delta.content or ""
                full_response += delta
                placeholder.markdown(full_response + "▌")
            placeholder.markdown(full_response)
        except Exception as e:
            error_text = str(e).lower()
            if "rate_limit" in error_text or "429" in error_text:
                full_response = (
                    "⚠️ Daily token limit reached for this API key. Two options: "
                    "(1) copy your latest SESSION STATE block and continue "
                    "tomorrow, or (2) enter your own free Groq API key in the "
                    "sidebar (get one at console.groq.com) to continue right now."
                )
            else:
                full_response = f"⚠️ Error calling the Groq API: {e}"
            placeholder.markdown(full_response)

    st.session_state.messages.append(
        {"role": "assistant", "content": full_response}
    )
    update_captured()


# ---------------------------------------------------------------------------
# STATE INIT
# ---------------------------------------------------------------------------
if "messages" not in st.session_state:
    st.session_state.messages = [{"role": "assistant", "content": GREETING}]
st.session_state.setdefault("current_module", MODULE_KEYS[0])
st.session_state.setdefault("captured", {})
st.session_state.setdefault("pending_open", False)

# ---------------------------------------------------------------------------
# UI — SIDEBAR
# ---------------------------------------------------------------------------
with st.sidebar:
    st.markdown("### 🧭 Innovation Process Navigator")
    st.caption(
        "Based on the SEPT Innovation Process framework · Universität Leipzig"
    )
    st.divider()

    # --- Module control ---
    current_idx = MODULE_KEYS.index(st.session_state.current_module)
    st.markdown(f"📍 **Current module:** {MODULE_LABELS[st.session_state.current_module]}")
    st.caption(f"Step {current_idx + 1} of {len(MODULES)}")

    chosen = st.selectbox(
        "Jump to module",
        MODULE_KEYS,
        index=current_idx,
        format_func=lambda k: MODULE_LABELS[k],
        help=(
            "Normally you advance with the Continue button. Use this to jump "
            "straight to a specific step."
        ),
    )
    if chosen != st.session_state.current_module:
        st.session_state.current_module = chosen
        st.rerun()

    is_last = current_idx == len(MODULES) - 1
    if st.button(
        "✅ Continue to next module",
        type="primary",
        disabled=is_last,
        use_container_width=True,
    ):
        next_key = MODULE_KEYS[current_idx + 1]
        st.session_state.current_module = next_key
        st.session_state.messages.append(
            {
                "role": "assistant",
                "content": f"➡️ Moving to Module {MODULE_LABELS[next_key]}.",
            }
        )
        st.session_state.pending_open = True
        st.rerun()

    st.divider()

    # --- Session state (code-generated) ---
    with st.expander("💾 Session state"):
        st.code(render_session_state_block())
        st.caption(
            "Copy this to resume later. Paste it back as your first message "
            "in a new session."
        )

    st.divider()
    st.session_state.user_api_key = st.text_input(
        "Your Groq API key (optional)",
        value=st.session_state.get("user_api_key", ""),
        type="password",
        help=(
            "Each team can use their own free key from console.groq.com so you "
            "don't share a daily limit. Leave blank to use the default key."
        ),
    )
    st.divider()
    if st.button("🔄 Reset conversation"):
        st.session_state.messages = [{"role": "assistant", "content": GREETING}]
        st.session_state.current_module = MODULE_KEYS[0]
        st.session_state.captured = {}
        st.session_state.pending_open = False
        st.rerun()
    st.caption(
        "This agent is an educational tool. Its outputs are structured "
        "drafts, not professional, legal, or financial advice."
    )
    st.divider()
    st.markdown("#### 🔗 Companion tools")
    st.link_button("Value Proposition Canvas", VPC_URL)
    st.link_button("Quality Function Deployment (QFD)", QFD_URL)

st.title("🧭 Innovation Process Navigator")

# ---------------------------------------------------------------------------
# RENDER HISTORY
# ---------------------------------------------------------------------------
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# ---------------------------------------------------------------------------
# CONTINUE-BUTTON FOLLOW-UP: open the new module automatically
# ---------------------------------------------------------------------------
if st.session_state.pending_open:
    st.session_state.pending_open = False
    run_assistant_turn()
    st.rerun()

# ---------------------------------------------------------------------------
# CHAT INPUT
# ---------------------------------------------------------------------------
user_input = st.chat_input("Type your answer here...")

if user_input:
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    # If the user pastes a SESSION STATE block, load it instead of treating it
    # as a normal answer.
    if "=== SESSION STATE" in user_input:
        parsed = parse_pasted_session_state(user_input)
        target_module = parsed.pop("current_module", None)
        merge_captured(parsed)
        if target_module:
            st.session_state.current_module = target_module
        label = MODULE_LABELS[st.session_state.current_module]
        welcome_back = (
            f"✅ Welcome back — I've loaded your saved progress. We're at "
            f"**Module {label}**. Continuing from there — tell me when you're "
            f"ready, or just answer the current step."
        )
        st.session_state.messages.append(
            {"role": "assistant", "content": welcome_back}
        )
        st.rerun()
    else:
        run_assistant_turn()
